config/routes.rb
Rails.application.routes.draw do
  resources :tipo_de_pagos
  root "tikets#index"
  resources :tikets


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tiket.rb
class Tiket < ApplicationRecord
  has_one_attached :file, dependent: :destroy
  belongs_to :tipo_de_pago, optional: true
  monetize :monto_cents




  validates :tipo_de_pago_id, presence: true









end

app/models/tipo_de_pago.rb
class TipoDePago < ApplicationRecord
  has_many :tikets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tikets_controller.rb
class TiketsController < ApplicationController
  before_action :set_tiket, only: %i[ show edit update destroy ]

  # GET /tikets or /tikets.json
  def index
    @tikets = Tiket.all
  end

  # GET /tikets/1 or /tikets/1.json
  def show
  end

  # GET /tikets/new
  def new
    @tiket = Tiket.new
  end

  # GET /tikets/1/edit
  def edit
  end

  # POST /tikets or /tikets.json
  def create
    @tiket = Tiket.new(tiket_params)

    respond_to do |format|
      if @tiket.save
        format.html { redirect_to tiket_url(@tiket), notice: "Tiket was successfully created." }
        format.json { render :show, status: :created, location: @tiket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tiket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tikets/1 or /tikets/1.json
  def update
    respond_to do |format|
      if @tiket.update(tiket_params)
        format.html { redirect_to tiket_url(@tiket), notice: "Tiket was successfully updated." }
        format.json { render :show, status: :ok, location: @tiket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tiket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tikets/1 or /tikets/1.json
  def destroy
    @tiket.destroy!

    respond_to do |format|
      format.html { redirect_to tikets_url, notice: "Tiket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tiket
      @tiket = Tiket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tiket_params
      params.require(:tiket).permit(:fecha, :monto, :monto_cents, :descripcion, :file, :tipo_de_pago_id)
    end
end

app/controllers/tipo_de_pagos_controller.rb
class TipoDePagosController < ApplicationController
  before_action :set_tipo_de_pago, only: %i[ show edit update destroy ]

  # GET /tipo_de_pagos or /tipo_de_pagos.json
  def index
    @tipo_de_pagos = TipoDePago.all
  end

  # GET /tipo_de_pagos/1 or /tipo_de_pagos/1.json
  def show
  end

  # GET /tipo_de_pagos/new
  def new
    @tipo_de_pago = TipoDePago.new
  end

  # GET /tipo_de_pagos/1/edit
  def edit
  end

  # POST /tipo_de_pagos or /tipo_de_pagos.json
  def create
    @tipo_de_pago = TipoDePago.new(tipo_de_pago_params)

    respond_to do |format|
      if @tipo_de_pago.save
        format.html { redirect_to tipo_de_pago_url(@tipo_de_pago), notice: "Tipo de pago was successfully created." }
        format.json { render :show, status: :created, location: @tipo_de_pago }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tipo_de_pago.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_de_pagos/1 or /tipo_de_pagos/1.json
  def update
    respond_to do |format|
      if @tipo_de_pago.update(tipo_de_pago_params)
        format.html { redirect_to tipo_de_pago_url(@tipo_de_pago), notice: "Tipo de pago was successfully updated." }
        format.json { render :show, status: :ok, location: @tipo_de_pago }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tipo_de_pago.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_de_pagos/1 or /tipo_de_pagos/1.json
  def destroy
    @tipo_de_pago.destroy!

    respond_to do |format|
      format.html { redirect_to tipo_de_pagos_url, notice: "Tipo de pago was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_de_pago
      @tipo_de_pago = TipoDePago.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tipo_de_pago_params
      params.require(:tipo_de_pago).permit(:metodo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tikets_helper.rb
module TiketsHelper
end

app/helpers/tipo_de_pagos_helper.rb
module TipoDePagosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VerGasto</title>

    

    


    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all","data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <%= image_tag("vergastologch.png", alt: "logo", class: "logdob") %>


  <body>
    <%= yield %>
  </body>

  <h6>Ver Gasto &#169; 2024 by unknownshoppers.com</h6>
</html>

app/views/tikets/_attachment.html.erb
<% if tiket.file.attached? %>
    <div class="row">
        <% if tiket.file.image? %>
            <div class="message_image-container">
                <%= image_tag(tiket.file, class:"message-image") %>
            </div>
        
    <% elsif tiket.file.video?%>
        <%= video_tag(url_for(tiket.file), class:"message-video", controls: "") %>
        <% elsif tiket.file.audio?%>
        <%= audio_tag(url_for(tiket.file), class:"message-audio", controls: "") %>
        <% else %>
        <%= link_to tiket.file.filename,url_for(tiket.file), class:"message-file" %>

    <% end %>
    </div>
<% end %>
    

app/views/tikets/_form.html.erb
<%= form_with(model: tiket) do |form| %>
  <% if tiket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tiket.errors.count, "error") %> prohibited this tiket from being saved:</h2>

      <ul>
        <% tiket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  

  <div>
    <%= form.label :fecha, style: "display: block" %>
    <%= form.date_field :fecha %>
  </div>

    <div>
    <%= form.label :monto, style: "display: block" %>
    <%= form.text_field :monto %>
  </div>

  <div>
    <%= form.label :Tarjeta_o_Efectivo, style: "display: block" %>
    
    
    <%= form.collection_select :tipo_de_pago_id, TipoDePago.all, :id, :metodo, include_blank: "Selecciona el metodo de pago" %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_area :descripcion %>
  </div>

  <div>
    <%= form.label :file, style: "display: block" %>
    <%= form.file_field :file %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tikets/_tiket.html.erb
<div id="<%= dom_id tiket %>">
  <p>
    <strong>Fecha:</strong>
    <%= tiket.fecha %>
  </p>

  <p>
    <strong>Monto:</strong>
    <%= humanized_money_with_symbol tiket.monto %>
  </p>

  <p>
    <strong>Tarjeta o Efectivo:</strong>
    <% if tiket.tipo_de_pago %>
      
    <%= tiket.tipo_de_pago.metodo.upcase %>
      <% end %>
      
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= tiket.descripcion %>
  </p>
  <p>
    <%= render 'tikets/attachment', tiket: tiket %>
  </p>

</div>

app/views/tikets/edit.html.erb
<h1>Edición de tiket</h1>

<%= render "form", tiket: @tiket %>

<br>

<div>
  <%= link_to "Ver tiket", @tiket %> |
  <%= link_to "Regresar a tikets", tikets_path %>
</div>

app/views/tikets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1></h1>

<%= link_to "Nuevo tiket", new_tiket_path %>

<div id="tikets">
  <% @tikets.each do |tiket| %>
    <%= render tiket %>
    <p>
      <%= link_to "Mostrar tiket", tiket %>
    </p>
  <% end %>
</div>

<%= link_to "Nuevo tiket", new_tiket_path %>

app/views/tikets/new.html.erb
<h1>Nuevo Tiket</h1>


<%= render "form", tiket: @tiket %>

<br>

<div >
  <%= link_to "Regresar a tikets", tikets_path %>
</div>

app/views/tikets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tiket %>

<div>
  <%= link_to "Editar tiket", edit_tiket_path(@tiket) %> |
  <%= link_to "Regresar a tikets", tikets_path %>

  <%= button_to "Destruir tiket", @tiket, method: :delete %>
</div>

app/views/tipo_de_pagos/_form.html.erb
<%= form_with(model: tipo_de_pago) do |form| %>
  <% if tipo_de_pago.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tipo_de_pago.errors.count, "error") %> prohibited this tipo_de_pago from being saved:</h2>

      <ul>
        <% tipo_de_pago.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :metodo, style: "display: block" %>
    <%= form.text_field :metodo %>
  </div>

  

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tipo_de_pagos/_tipo_de_pago.html.erb
<div id="<%= dom_id tipo_de_pago %>">
  <p>
    <strong>Metodo:</strong>
    <%= tipo_de_pago.metodo %>
  </p>

  

</div>

app/views/tipo_de_pagos/edit.html.erb
<h1>Editing tipo de pago</h1>

<%= render "form", tipo_de_pago: @tipo_de_pago %>

<br>

<div>
  <%= link_to "Show this tipo de pago", @tipo_de_pago %> |
  <%= link_to "Back to tipo de pagos", tipo_de_pagos_path %>
</div>

app/views/tipo_de_pagos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tipo de pagos</h1>

<div id="tipo_de_pagos">
  <% @tipo_de_pagos.each do |tipo_de_pago| %>
    <%= render tipo_de_pago %>
    <p>
      <%= link_to "Show this tipo de pago", tipo_de_pago %>
    </p>
  <% end %>
</div>

<%= link_to "New tipo de pago", new_tipo_de_pago_path %>

app/views/tipo_de_pagos/new.html.erb
<h1>New tipo de pago</h1>

<%= render "form", tipo_de_pago: @tipo_de_pago %>

<br>

<div>
  <%= link_to "Back to tipo de pagos", tipo_de_pagos_path %>
</div>

app/views/tipo_de_pagos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tipo_de_pago %>

<div>
  <%= link_to "Edit this tipo de pago", edit_tipo_de_pago_path(@tipo_de_pago) %> |
  <%= link_to "Back to tipo de pagos", tipo_de_pagos_path %>

  <%= button_to "Destroy this tipo de pago", @tipo_de_pago, method: :delete %>
</div>